export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerName: process.env.OWNER_NAME?.trim() || "مؤسس EduPulse",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  medusaBackendUrl: process.env.MEDUSA_BACKEND_URL?.replace(/\/+$/, "") ?? "",
  medusaPublishableKey: process.env.MEDUSA_PUBLISHABLE_KEY ?? "",
  medusaAdminToken: process.env.MEDUSA_ADMIN_TOKEN ?? "",
  veniceInferenceApiKey: process.env.VENICE_INFERENCE_API_KEY ?? "",
  veniceBaseUrl: process.env.VENICE_BASE_URL ?? "https://api.venice.ai/api/v1",
  veniceModel: process.env.VENICE_MODEL ?? "llama-3.3-70b",
};
