import { Loader2, ShieldAlert, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function GuardianPortalPanel({ isArabic }: { isArabic: boolean }) {
  const query = trpc.records.guardianLearners.useQuery(undefined, { retry: false });
  if (query.isLoading) return <div className="surface-panel flex min-h-64 items-center justify-center rounded-2xl"><Loader2 className="h-5 w-5 animate-spin text-white/60" /></div>;
  if (query.error) return <div className="surface-panel rounded-2xl p-6" dir={isArabic ? "rtl" : "ltr"}><ShieldAlert className="h-6 w-6 text-amber-100/70" /><h2 className="text-display mt-8 text-4xl">{isArabic ? "تعذر فتح سجل الأسرة." : "Family records unavailable."}</h2><p className="mt-4 text-sm leading-7 text-white/55">{isArabic ? "تواصل مع مسؤول المؤسسة لربط حسابك بسجل الطالب. لا نعرض سجلاً غير مرتبط." : "Ask an institution administrator to link your account to a learner. Unlinked records are never shown."}</p></div>;
  const rows = query.data ?? [];
  return <div className="space-y-6" dir={isArabic ? "rtl" : "ltr"}><section><p className="mb-2 text-xs uppercase tracking-[0.2em] text-white/45">{isArabic ? "بوابة ولي الأمر" : "Guardian portal"}</p><h2 className="text-display text-5xl">{isArabic ? "متابعة واضحة." : "A clear family view."}</h2><p className="mt-3 text-sm text-white/55">{isArabic ? "تظهر فقط سجلات الطلاب المرتبطة بحسابك داخل المؤسسة." : "Only learners explicitly linked to your account appear here."}</p></section><div className="grid gap-4 md:grid-cols-2">{rows.length ? rows.map(({ learner }) => <article key={learner.id} className="surface-panel rounded-2xl p-6"><UsersRound className="h-5 w-5 text-white/55" /><p className="text-display mt-8 text-3xl">{isArabic ? learner.nameAr : learner.name}</p><p className="mt-2 text-sm text-white/50">{learner.grade}</p><div className="mt-6 rounded-xl border border-white/10 px-4 py-3 text-xs text-emerald-100/80">{isArabic ? "سجل مرتبط ومحمّي" : "Linked and protected record"}</div></article>) : <div className="surface-panel rounded-2xl p-6 text-sm leading-7 text-white/55">{isArabic ? "لم يربط المسؤول أي طالب بحسابك بعد." : "No learner has been linked to your account yet."}</div>}</div></div>;
}
