import { useEffect, useState, type FormEvent } from "react";
import { KeyRound, Loader2, ShieldCheck } from "lucide-react";
import { isDesktopRuntime } from "@/lib/desktopRuntime";
import { localAuthStatus, localLogin, localRegisterOwner } from "@/lib/localAuthDesktop";

type Language = "ar" | "en";
type LocalUser = { id: number; institution_id: string; first_name: string; family_name: string; email: string; designation: string; role: string };
type Props = { language: Language; onAuthenticated: (user: LocalUser, sessionToken: string) => void; onBack: () => void; onLanguageChange: (language: Language) => void };

type OwnerForm = { firstName: string; familyName: string; birthplace: string; dateOfBirth: string; sex: string; institutionName: string; designation: string; email: string; password: string; confirmation: string };
const emptyOwner: OwnerForm = { firstName: "", familyName: "", birthplace: "", dateOfBirth: "", sex: "", institutionName: "", designation: "", email: "", password: "", confirmation: "" };
const copy = { ar: { setup: "إنشاء مساحة المؤسسة", login: "تسجيل الدخول المحلي", setupNote: "أنشئ حساب مدير المؤسسة على هذا الكمبيوتر. تُحفظ البيانات داخل قاعدة SQLCipher المشفّرة.", loginNote: "أدخل بيانات حسابك المحلي لفتح مساحة EduPulse.", first: "الاسم", family: "اسم العائلة", birthplace: "مكان الميلاد", dob: "تاريخ الميلاد", sex: "الجنس", institution: "اسم المؤسسة", designation: "الصفة / المنصب", email: "البريد الإلكتروني أو اسم المستخدم", password: "كلمة المرور", confirmation: "تأكيد كلمة المرور", submitSetup: "إنشاء حساب المدير", submitLogin: "فتح المساحة", switchLogin: "لدي حساب على هذا الكمبيوتر", switchSetup: "إنشاء حساب المدير الأول", back: "العودة إلى المنصة", required: "جميع الحقول مطلوبة.", mismatch: "كلمتا المرور غير متطابقتين.", passwordRule: "10 أحرف على الأقل، مع حرف كبير وحرف صغير ورقم.", unavailable: "هذه الشاشة تعمل داخل تطبيق Windows EduPulse فقط.", failed: "تعذر إتمام العملية. تحقق من البيانات وحاول مرة أخرى." }, en: { setup: "Create institution space", login: "Local sign in", setupNote: "Create the institution manager account on this computer. Data is stored in the encrypted SQLCipher database.", loginNote: "Enter your local account details to open EduPulse.", first: "First name", family: "Family name", birthplace: "Birthplace", dob: "Date of birth", sex: "Sex", institution: "Institution name", designation: "Designation / title", email: "Email or username", password: "Password", confirmation: "Confirm password", submitSetup: "Create manager account", submitLogin: "Open workspace", switchLogin: "I already have an account on this computer", switchSetup: "Create the first manager account", back: "Back to platform", required: "Every field is required.", mismatch: "The passwords do not match.", passwordRule: "At least 10 characters, including uppercase, lowercase, and a number.", unavailable: "This screen works inside the EduPulse Windows app only.", failed: "The operation could not be completed. Check your details and try again." } };

export function LocalAuthPanel({ language, onAuthenticated, onBack, onLanguageChange }: Props) {
  const t = copy[language];
  const [hasOwner, setHasOwner] = useState<boolean | null>(null);
  const [mode, setMode] = useState<"setup" | "login">("login");
  const [form, setForm] = useState<OwnerForm>(emptyOwner);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { localAuthStatus().then((exists) => { setHasOwner(exists); setMode(exists ? "login" : "setup"); }).catch(() => setError(t.unavailable)); }, [t.unavailable]);
  const update = (key: keyof OwnerForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (mode === "setup" && Object.values(form).some((value) => !value.trim())) { setError(t.required); return; } if (mode === "setup" && form.password !== form.confirmation) { setError(t.mismatch); return; } setBusy(true); try { if (mode === "setup") { const user = await localRegisterOwner({ first_name: form.firstName, family_name: form.familyName, birthplace: form.birthplace, date_of_birth: form.dateOfBirth, sex: form.sex, institution_name: form.institutionName, designation: form.designation, email: form.email, password: form.password }); const session = await localLogin(form.email, form.password); onAuthenticated(user, session.sessionToken); } else { const session = await localLogin(form.email, form.password); onAuthenticated(session.user, session.sessionToken); } } catch (reason) { setError(reason instanceof Error ? reason.message : t.failed); } finally { setBusy(false); } };
  if (!isDesktopRuntime()) return <section className="mx-auto max-w-xl rounded-[2rem] border border-white/20 bg-[#002334]/95 p-8 text-white"><p>{t.unavailable}</p></section>;
  const field = (key: keyof OwnerForm, label: string, type = "text") => <label className="block"><span className="mb-2 block text-xs text-white/70">{label}</span><input required type={type} value={form[key]} onChange={(event) => update(key, event.target.value)} className="w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm text-white outline-none transition focus:border-emerald-200/70" /></label>;
  return <section className="relative z-10 mx-auto w-full max-w-2xl rounded-[2rem] border border-white/25 bg-[#002334]/[0.98] p-6 text-white shadow-[0_24px_90px_rgba(0,0,0,0.55)] sm:p-9" dir={language === "ar" ? "rtl" : "ltr"}>
    <div className="mb-7 flex items-center justify-between gap-4"><button type="button" onClick={onBack} className="text-xs text-white/75 hover:text-white">{t.back}</button><button type="button" onClick={() => onLanguageChange(language === "ar" ? "en" : "ar")} className="rounded-full border border-white/20 px-3 py-2 text-xs text-white/75">{language === "ar" ? "English" : "العربية"}</button></div>
    <div className="mb-7 rounded-2xl border border-emerald-100/15 bg-emerald-100/[0.06] p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-200" /><p className="text-xs uppercase tracking-[0.16em] text-emerald-100/75">EduPulse · {mode === "setup" ? t.setup : t.login}</p></div><h1 className="mt-4 text-3xl font-semibold">{mode === "setup" ? t.setup : t.login}</h1><p className="mt-3 text-sm leading-7 text-white/70">{mode === "setup" ? t.setupNote : t.loginNote}</p></div>
    <form onSubmit={submit} className="space-y-4">{mode === "setup" && <div className="grid gap-4 sm:grid-cols-2">{field("firstName", t.first)}{field("familyName", t.family)}{field("birthplace", t.birthplace)}{field("dateOfBirth", t.dob, "date")}{field("sex", t.sex)}{field("institutionName", t.institution)}{field("designation", t.designation)}</div>}{field("email", t.email, "email")}{field("password", t.password, "password")}{mode === "setup" && <>{field("confirmation", t.confirmation, "password")}<p className="text-xs leading-5 text-white/50">{t.passwordRule}</p></>} {error && <p role="alert" className="rounded-xl border border-amber-200/25 bg-amber-100/10 px-4 py-3 text-sm text-amber-100">{error}</p>}<button disabled={busy || hasOwner === null} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-200 px-5 py-3.5 text-sm font-semibold text-[#003c3c] transition hover:bg-emerald-100 disabled:cursor-wait disabled:opacity-60">{busy && <Loader2 className="h-4 w-4 animate-spin" />}{mode === "setup" ? t.submitSetup : t.submitLogin}</button></form>
    {hasOwner !== null && <button type="button" onClick={() => { setMode(mode === "setup" ? "login" : "setup"); setError(""); }} className="mt-6 w-full text-center text-xs text-white/60 hover:text-white">{mode === "setup" ? t.switchLogin : t.switchSetup}</button>}
    <div className="mt-6 flex items-center gap-2 rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-xs text-white/50"><KeyRound className="h-4 w-4 shrink-0" />{language === "ar" ? "مفتاح قاعدة البيانات لا يغادر مخزن بيانات اعتماد Windows." : "The database key never leaves the Windows credential store."}</div>
  </section>;
}
