import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BrainCircuit, CheckCircle2, Loader2, ShieldAlert, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type Props = { isArabic: boolean };

export function StudentSupportEvaluationPanel({ isArabic }: Props) {
  const [learnerId, setLearnerId] = useState("");
  const learners = trpc.records.learners.useQuery(undefined, { retry: false });
  const assessments = trpc.records.learningAssessments.useQuery({ learnerId }, { enabled: Boolean(learnerId), retry: false });
  const evaluations = trpc.records.supportEvaluations.useQuery({ learnerId }, { enabled: Boolean(learnerId), retry: false });
  const utils = trpc.useUtils();
  const generate = trpc.records.generateSupportEvaluation.useMutation({ onSuccess: () => { toast.success(isArabic ? "تم إنشاء التقييم للمراجعة." : "Evaluation created for review."); void utils.records.supportEvaluations.invalidate(); void utils.records.learningAssessments.invalidate(); }, onError: error => toast.error(error.message) });
  const review = trpc.records.reviewSupportEvaluation.useMutation({ onSuccess: () => { toast.success(isArabic ? "تم تحديث حالة المراجعة." : "Review status updated."); void utils.records.supportEvaluations.invalidate(); }, onError: error => toast.error(error.message) });
  const selected = learners.data?.find(item => item.id === learnerId);
  const chartData = useMemo(() => (assessments.data || []).slice().reverse().map(item => ({ date: new Date(item.assessedAt).toLocaleDateString(isArabic ? "ar-DZ" : "en-GB", { month: "short", day: "numeric" }), subject: item.subject, score: item.score })), [assessments.data, isArabic]);
  const latest = evaluations.data?.[0];
  const parse = (value: string | null | undefined) => { try { return value ? JSON.parse(value) as unknown : []; } catch { return []; } };
  const evidence = latest ? parse(latest.evidenceJson) as { averageScore?: number | null; attendanceRate?: number | null; strongSubjects?: string[]; weakSubjects?: string[]; subjectTrends?: Array<{ subject: string; average: number }> } : null;
  const factors = latest ? parse(latest.factorsJson) as string[] : [];
  const recommendations = latest ? parse(latest.recommendationsJson) as string[] : [];
  return <div className="space-y-6" dir={isArabic ? "rtl" : "ltr"}>
    <section className="surface-panel rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-display text-3xl">{isArabic ? "تقييم التعلم والدعم" : "Learning & support review"}</p><p className="mt-2 max-w-3xl text-sm leading-7 text-white/55">{isArabic ? "تحليل مساعد للمعلم من المرحلة التحضيرية إلى التعليم العالي. يعتمد على أدلة المؤسسة، ولا يشخّص حالة نفسية أو طبية." : "A teacher support analysis from preparatory through higher education. It uses institution evidence and does not diagnose psychological or medical conditions."}</p></div><BrainCircuit className="h-6 w-6 text-cyan-200" /></div>
      <div className="mt-5 grid gap-3 md:grid-cols-[1fr_auto]"> <select value={learnerId} onChange={event => setLearnerId(event.target.value)} className="rounded-xl border border-white/10 bg-[#07394a] px-3 py-3 text-sm text-white outline-none"><option value="">{isArabic ? "اختر المتعلم" : "Choose learner"}</option>{learners.data?.map(item => <option key={item.id} value={item.id}>{isArabic ? item.nameAr : item.name} · {item.grade}</option>)}</select><button disabled={!learnerId || generate.isPending} onClick={() => learnerId && generate.mutate({ learnerId, language: isArabic ? "ar" : "en" })} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-200 px-5 py-3 text-sm text-[#00364A] disabled:opacity-40">{generate.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{isArabic ? "إنشاء مراجعة" : "Generate review"}</button></div>
      <div className="mt-4 flex items-center gap-2 text-xs text-white/45"><ShieldAlert className="h-4 w-4" />{isArabic ? "متاح للموظفين المصرح لهم فقط. يجب مراجعة النتيجة قبل مشاركتها." : "Authorized staff only. Review the result before sharing it."}</div>
    </section>
    {selected && <><section className="surface-panel rounded-2xl p-6"><div className="flex items-center justify-between"><div><p className="text-display text-2xl">{isArabic ? "منحنى التعلم" : "Learning trend"}</p><p className="mt-1 text-sm text-white/50">{selected.nameAr} · {selected.grade}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/55">{assessments.data?.length || 0} {isArabic ? "تقييمات" : "assessments"}</span></div><div className="mt-5 h-64">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="supportScore" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#67e8f9" stopOpacity={0.55} /><stop offset="95%" stopColor="#67e8f9" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.08)" /><XAxis dataKey="date" stroke="rgba(255,255,255,.55)" /><YAxis domain={[0, 100]} stroke="rgba(255,255,255,.55)" /><Tooltip contentStyle={{ background: "#07394a", border: "1px solid rgba(255,255,255,.15)", borderRadius: 12 }} /><Area type="monotone" dataKey="score" stroke="#67e8f9" fill="url(#supportScore)" /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-xl border border-dashed border-white/10 text-sm text-white/45">{isArabic ? "أضف تقييمات للمتعلم لعرض المنحنى." : "Add learner assessments to display the trend."}</div>}</div></section>
    {latest && <section className="grid gap-4 lg:grid-cols-3"><article className="surface-panel rounded-2xl p-5"><p className="text-xs text-white/50">{isArabic ? "مستوى الدعم" : "Support level"}</p><p className="mt-3 text-2xl font-semibold">{latest.supportLevel === "progressing" ? (isArabic ? "يتقدم" : "Progressing") : latest.supportLevel === "needs_support" ? (isArabic ? "يحتاج دعماً" : "Needs support") : (isArabic ? "مراجعة عاجلة" : "Urgent review")}</p><p className="mt-3 text-sm leading-6 text-white/60">{latest.aiSummary}</p></article><article className="surface-panel rounded-2xl p-5"><p className="text-xs text-white/50">{isArabic ? "الأدلة" : "Evidence"}</p><div className="mt-3 space-y-2 text-sm text-white/70"><p>{isArabic ? "المتوسط" : "Average"}: {evidence?.averageScore ?? "—"}</p><p>{isArabic ? "الحضور" : "Attendance"}: {evidence?.attendanceRate ?? "—"}%</p><p>{isArabic ? "نقاط القوة" : "Strengths"}: {evidence?.strongSubjects?.join(", ") || "—"}</p><p>{isArabic ? "مجالات الدعم" : "Support areas"}: {evidence?.weakSubjects?.join(", ") || "—"}</p></div></article><article className="surface-panel rounded-2xl p-5"><p className="text-xs text-white/50">{isArabic ? "حالة المراجعة" : "Review state"}</p><p className="mt-3 text-lg">{latest.status}</p><button onClick={() => review.mutate({ evaluationId: latest.id, status: latest.status === "draft" ? "reviewed" : "shared" })} disabled={review.isPending} className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs text-[#00364A] disabled:opacity-40"><CheckCircle2 className="h-3.5 w-3.5" />{latest.status === "draft" ? (isArabic ? "اعتماد للمراجعة" : "Mark reviewed") : (isArabic ? "مشاركة" : "Share with approved staff")}</button></article></section>}
    {latest && <section className="grid gap-4 lg:grid-cols-2"><article className="surface-panel rounded-2xl p-5"><p className="text-display text-2xl">{isArabic ? "عوامل محتملة تحتاج تحققاً" : "Possible contributing factors to verify"}</p><ul className="mt-4 space-y-3 text-sm leading-6 text-white/65">{factors.map(item => <li key={item}>• {item}</li>)}</ul></article><article className="surface-panel rounded-2xl p-5"><p className="text-display text-2xl">{isArabic ? "خطة المتابعة المقترحة" : "Suggested follow-up"}</p><ul className="mt-4 space-y-3 text-sm leading-6 text-white/65">{recommendations.map(item => <li key={item}>• {item}</li>)}</ul></article></section>}</>}
  </div>;
}
