import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BrainCircuit, CheckCircle2, Gauge, Loader2, ShieldAlert, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { ALGERIA_EDUCATION_STAGES, educationStageLabel } from "@shared/educationStages";

type Props = { isArabic: boolean };
type Evidence = { averageScore?: number | null; attendanceRate?: number | null; strongSubjects?: string[]; weakSubjects?: string[]; subjectTrends?: Array<{ subject: string; average: number; latest?: number; assessments?: number }> };

function parseJson<T>(value: string | null | undefined, fallback: T): T { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }

export function StudentSupportEvaluationPanel({ isArabic }: Props) {
  const [learnerId, setLearnerId] = useState("");
  const [stageFilter, setStageFilter] = useState<"all" | "preparatory" | "primary" | "middle" | "secondary" | "higher">("all");
  const [sortBy, setSortBy] = useState<"name" | "stage">("name");
  const learners = trpc.records.learners.useQuery(undefined, { retry: false });
  const assessments = trpc.records.learningAssessments.useQuery({ learnerId }, { enabled: Boolean(learnerId), retry: false });
  const evaluations = trpc.records.supportEvaluations.useQuery({ learnerId }, { enabled: Boolean(learnerId), retry: false });
  const utils = trpc.useUtils();
  const generate = trpc.records.generateSupportEvaluation.useMutation({ onSuccess: () => { toast.success(isArabic ? "تم تشغيل Venice وإنشاء نتيجة للمراجعة." : "Venice evaluation completed for review."); void utils.records.supportEvaluations.invalidate(); void utils.records.learningAssessments.invalidate(); }, onError: error => toast.error(error.message) });
  const review = trpc.records.reviewSupportEvaluation.useMutation({ onSuccess: () => { toast.success(isArabic ? "تم تحديث حالة المراجعة." : "Review status updated."); void utils.records.supportEvaluations.invalidate(); }, onError: error => toast.error(error.message) });
  const filteredLearners = useMemo(() => (learners.data ?? []).filter(item => stageFilter === "all" || item.grade === stageFilter).sort((a, b) => sortBy === "stage" ? educationStageLabel(a.grade, isArabic).localeCompare(educationStageLabel(b.grade, isArabic), isArabic ? "ar" : "en") : (isArabic ? a.nameAr : a.name).localeCompare(isArabic ? b.nameAr : b.name, isArabic ? "ar" : "en")), [learners.data, stageFilter, sortBy, isArabic]);
  const selected = learners.data?.find(item => item.id === learnerId);
  const latest = evaluations.data?.[0];
  const evidence = latest ? parseJson<Evidence>(latest.evidenceJson, {}) : null;
  const factors = latest ? parseJson<string[]>(latest.factorsJson, []) : [];
  const recommendations = latest ? parseJson<string[]>(latest.recommendationsJson, []) : [];
  const chartData = useMemo(() => (assessments.data || []).slice().reverse().map(item => ({ date: new Date(item.assessedAt).toLocaleDateString(isArabic ? "ar-DZ" : "en-GB", { month: "short", day: "numeric" }), subject: item.subject, score: item.score })), [assessments.data, isArabic]);
  const subjectData = evidence?.subjectTrends ?? [];
  const runEvaluation = () => { if (learnerId) generate.mutate({ learnerId, language: isArabic ? "ar" : "en" }); };
  const level = latest?.supportLevel === "progressing" ? { ar: "يتقدم", en: "Progressing", className: "bg-emerald-50 text-emerald-800" } : latest?.supportLevel === "needs_support" ? { ar: "يحتاج دعماً", en: "Needs support", className: "bg-amber-50 text-amber-800" } : { ar: "مراجعة عاجلة", en: "Urgent review", className: "bg-rose-50 text-rose-800" };

  return <div className="space-y-6" dir={isArabic ? "rtl" : "ltr"}>
    <section className="rounded-[28px] bg-gradient-to-br from-white via-[#f7fdff] to-[#fff8d9] p-6 text-[#0a3b52] shadow-[0_20px_60px_rgba(8,65,96,.12)] md:p-8">
      <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-start"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-cyan-200 bg-cyan-50 px-3 py-1 text-xs font-semibold text-cyan-800"><BrainCircuit className="h-4 w-4" />{isArabic ? "لوحة المعلم · Venice AI" : "Teacher dashboard · Venice AI"}</div><h2 className="text-display text-4xl tracking-tight md:text-5xl">{isArabic ? "صورة واضحة لتقدم المتعلم" : "A clear view of learner progress"}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#376276]">{isArabic ? "استخدم الأدلة التعليمية لتشغيل مراجعة Venice يدوياً. النتيجة مساعدة غير سريرية، وتبقى بحاجة إلى مراجعة المعلم قبل المشاركة." : "Use educational evidence to manually run a Venice review. The result is non-clinical support guidance and always requires teacher review before sharing."}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/85 p-4"><Gauge className="h-5 w-5 text-cyan-600" /><strong className="mt-3 block text-2xl">{evidence?.averageScore ?? "—"}</strong><span className="text-xs text-[#547083]">{isArabic ? "متوسط" : "Average"}</span></div><div className="rounded-2xl bg-white/85 p-4"><TrendingUp className="h-5 w-5 text-emerald-600" /><strong className="mt-3 block text-2xl">{evidence?.attendanceRate ?? "—"}%</strong><span className="text-xs text-[#547083]">{isArabic ? "حضور" : "Attendance"}</span></div><div className="rounded-2xl bg-white/85 p-4"><Sparkles className="h-5 w-5 text-amber-500" /><strong className="mt-3 block text-2xl">{evaluations.data?.length ?? 0}</strong><span className="text-xs text-[#547083]">{isArabic ? "مراجعات" : "Reviews"}</span></div></div></div>
      <div className="mt-7 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="block text-xs font-semibold text-[#376276]">{isArabic ? "المرحلة الجزائرية" : "Algerian stage"}<select value={stageFilter} onChange={event => setStageFilter(event.target.value as typeof stageFilter)} className="control-light mt-2 w-full px-4 py-3 text-sm"><option value="all">{isArabic ? "كل المراحل" : "All stages"}</option>{ALGERIA_EDUCATION_STAGES.map(stage => <option key={stage.id} value={stage.id}>{isArabic ? stage.ar : stage.en}</option>)}</select></label><label className="block text-xs font-semibold text-[#376276]">{isArabic ? "ترتيب القائمة" : "Sort learners"}<select value={sortBy} onChange={event => setSortBy(event.target.value as typeof sortBy)} className="control-light mt-2 w-full px-4 py-3 text-sm"><option value="name">{isArabic ? "حسب الاسم" : "By name"}</option><option value="stage">{isArabic ? "حسب المرحلة" : "By stage"}</option></select></label><label className="block text-xs font-semibold text-[#376276]">{isArabic ? "المتعلم" : "Learner"}<select value={learnerId} onChange={event => setLearnerId(event.target.value)} className="control-light mt-2 w-full px-4 py-3 text-sm"><option value="">{isArabic ? "اختر المتعلم" : "Choose learner"}</option>{filteredLearners.map(item => <option key={item.id} value={item.id}>{isArabic ? item.nameAr : item.name} · {educationStageLabel(item.grade, isArabic)}</option>)}</select></label><button type="button" disabled={!learnerId || generate.isPending} onClick={runEvaluation} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#0a6f88] px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-cyan-900/15 transition hover:bg-[#075a70] disabled:opacity-40">{generate.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{isArabic ? "تشغيل تقييم Venice" : "Run Venice evaluation"}</button></div>
      <div className="mt-4 flex items-center gap-2 text-xs text-[#547083]"><ShieldAlert className="h-4 w-4 text-cyan-700" />{isArabic ? "للموظفين المصرح لهم فقط · لا يوجد تشخيص نفسي أو طبي." : "Authorized staff only · no psychological or medical diagnosis."}</div>
    </section>
    {!selected && <div className="rounded-2xl border border-dashed border-cyan-200 bg-white/80 p-10 text-center text-sm text-[#547083]">{isArabic ? "اختر متعلماً لعرض المنحنى والنتيجة." : "Choose a learner to view the chart and evaluation."}</div>}
    {selected && <>
      <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><article className="rounded-[24px] bg-white p-6 text-[#0a3b52] shadow-[0_18px_45px_rgba(8,65,96,.1)]"><div className="flex items-start justify-between gap-4"><div><p className="text-display text-3xl">{isArabic ? "منحنى التعلم" : "Learning chart"}</p><p className="mt-1 text-sm text-[#547083]">{isArabic ? selected.nameAr : selected.name} · {educationStageLabel(selected.grade, isArabic)}</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs text-cyan-800">{assessments.data?.length || 0} {isArabic ? "تقييمات" : "assessments"}</span></div><div className="mt-5 h-72">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="supportScore" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#18a7c9" stopOpacity={0.5} /><stop offset="95%" stopColor="#18a7c9" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#dbeef2" /><XAxis dataKey="date" stroke="#6f8b98" /><YAxis domain={[0, 100]} stroke="#6f8b98" /><Tooltip contentStyle={{ background: "#ffffff", border: "1px solid #cceaf0", borderRadius: 14, color: "#0a3b52" }} /><Area type="monotone" dataKey="score" stroke="#0a91b2" strokeWidth={3} fill="url(#supportScore)" /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-2xl border border-dashed border-cyan-200 bg-cyan-50/40 text-sm text-[#547083]">{isArabic ? "أضف تقييمات للمتعلم لعرض المنحنى." : "Add assessments to display the learning chart."}</div>}</div></article><article className="rounded-[24px] bg-gradient-to-br from-[#e9fbff] to-[#fff8d9] p-6 text-[#0a3b52]"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-800">{isArabic ? "نتيجة المراجعة" : "Review result"}</p>{latest ? <><div className={`mt-4 inline-flex rounded-full px-4 py-2 text-sm font-semibold ${level.className}`}>{isArabic ? level.ar : level.en}</div><p className="mt-5 text-sm leading-7 text-[#376276]">{latest.aiSummary}</p><button type="button" onClick={() => review.mutate({ evaluationId: latest.id, status: latest.status === "draft" ? "reviewed" : "shared" })} disabled={review.isPending} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#0a6f88] px-4 py-2 text-xs font-semibold text-white disabled:opacity-40"><CheckCircle2 className="h-4 w-4" />{latest.status === "draft" ? (isArabic ? "اعتماد للمراجعة" : "Mark reviewed") : (isArabic ? "مشاركة مع الموظفين" : "Share with staff")}</button></> : <div className="mt-5 rounded-2xl bg-white/70 p-5 text-sm leading-7 text-[#547083]">{isArabic ? "لم يتم إنشاء مراجعة بعد. اضغط تشغيل تقييم Venice للحصول على نتيجة قابلة للمراجعة." : "No review yet. Run the Venice evaluation to create a reviewable result."}</div>}</article></section>
      {latest && <><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{subjectData.map(item => <article key={item.subject} className="rounded-2xl bg-white p-5 text-[#0a3b52] shadow-[0_12px_32px_rgba(8,65,96,.08)]"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{item.subject}</p>{(item.latest ?? item.average) >= item.average ? <TrendingUp className="h-4 w-4 text-emerald-600" /> : <TrendingDown className="h-4 w-4 text-rose-500" />}</div><strong className="mt-4 block text-3xl">{item.average}</strong><p className="mt-1 text-xs text-[#547083]">{isArabic ? "متوسط المادة" : "Subject average"}</p></article>)}</section><section className="grid gap-4 lg:grid-cols-2"><article className="rounded-[24px] bg-white p-6 text-[#0a3b52] shadow-[0_12px_32px_rgba(8,65,96,.08)]"><p className="text-display text-2xl">{isArabic ? "عوامل محتملة تحتاج تحققاً" : "Possible factors to verify"}</p><ul className="mt-4 space-y-3 text-sm leading-7 text-[#547083]">{factors.map(item => <li key={item} className="rounded-xl bg-amber-50 px-4 py-3">{item}</li>)}</ul></article><article className="rounded-[24px] bg-white p-6 text-[#0a3b52] shadow-[0_12px_32px_rgba(8,65,96,.08)]"><p className="text-display text-2xl">{isArabic ? "خطة المتابعة المقترحة" : "Suggested follow-up"}</p><ul className="mt-4 space-y-3 text-sm leading-7 text-[#547083]">{recommendations.map(item => <li key={item} className="rounded-xl bg-cyan-50 px-4 py-3">{item}</li>)}</ul></article></section></>}
    </>}
  </div>;
}
