import { Loader2, ShieldAlert, UserRound } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function StudentPortalPanel({ isArabic }: { isArabic: boolean }) {
  const query = trpc.records.myStudentRecord.useQuery(undefined, { retry: false });
  if (query.isLoading) return <div className="surface-panel flex min-h-64 items-center justify-center rounded-2xl"><Loader2 className="h-5 w-5 animate-spin text-white/60" /></div>;
  if (query.error) return <div className="surface-panel rounded-2xl p-6" dir={isArabic ? "rtl" : "ltr"}><ShieldAlert className="h-6 w-6 text-amber-100/70" /><h2 className="text-display mt-8 text-4xl">{isArabic ? "لا يوجد سجل مرتبط بعد." : "No linked record yet."}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/55">{isArabic ? "يجب على مسؤول المؤسسة ربط حسابك بسجل الطالب قبل عرض المعلومات الشخصية. لا نعرض سجلات طلاب آخرين كبديل." : "An institution administrator must link your account to a learner record before personal information can be shown. Other students’ records are never used as a fallback."}</p></div>;
  const learner = query.data;
  return <div className="space-y-6" dir={isArabic ? "rtl" : "ltr"}><section><p className="mb-2 text-xs uppercase tracking-[0.2em] text-white/45">{isArabic ? "بوابة الطالب" : "Student portal"}</p><h2 className="text-display text-5xl">{isArabic ? "سجلك، لك." : "Your record, yours."}</h2><p className="mt-3 text-sm text-white/55">{isArabic ? "تظهر هنا المعلومات المرتبطة بحسابك فقط." : "Only the record explicitly linked to your account appears here."}</p></section><article className="surface-panel rounded-2xl p-6"><div className="flex items-center gap-4"><div className="rounded-full border border-white/15 bg-white/5 p-3"><UserRound className="h-5 w-5 text-white/70" /></div><div><p className="text-display text-3xl">{isArabic ? learner?.nameAr : learner?.name}</p><p className="mt-1 text-sm text-white/45">{learner?.grade}</p></div></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/40">{isArabic ? "الحالة" : "Status"}</p><p className="mt-3 text-sm text-emerald-100">{learner?.status}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/40">{isArabic ? "السجل" : "Record"}</p><p className="mt-3 text-sm text-white/80">{learner?.id}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/40">{isArabic ? "الخصوصية" : "Privacy"}</p><p className="mt-3 text-sm text-white/80">{isArabic ? "مرتبط بحسابك" : "Account-linked"}</p></div></div></article></div>;
}
